FROM alpine

RUN apk -U add gcc musl-dev \
 && mkdir /data

WORKDIR /data

COPY main.c ignoresigchld.c /data
RUN gcc -Os -Wall -fdata-sections -ffunction-sections -Wl,--gc-sections -static -o docker_pid1 main.c \
 && strip -s docker_pid1 \
 && gcc -Os -Wall -fdata-sections -ffunction-sections -Wl,--gc-sections -static -o ignoresigchld ignoresigchld.c \
 && strip -s ignoresigchld


ENTRYPOINT ["/bin/tar", "c"]
